[package]
name = "graphrepresentations"
version = "0.0.1"
authors = ["Sebastian Schmidt <isibboi@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
